version: '3'
services:
  
  web:
    build:
      context: .
      dockerfile: ./Dockerfiledir/webd
    volumes:
      - ./data/mirror:/mirror
      - ./data/json:/json
    ports:
      - 9000:5001

  git:
    build:
      context: .
      dockerfile: ./Dockerfiledir/gitd
    volumes:
      - ./data/mirror:/mirror/git
      - ./data/json:/json/git

  httrack:
    build:
      context: .
      dockerfile: ./Dockerfiledir/httrackd
    volumes:
      - ./data/mirror:/mirror/httrack
      - ./data/json:/json/httrack
