version: '3'
services:
  
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./data/mirror:/mirror
      - ./data/json:/json
    ports:
      - 9000:5001


  youtube:
    build:
      context: .
      dockerfile: ./youtube/Dockerfile
    volumes:
      - ./data/mirror/youtube:/mirror/youtube/
      - ./data/json:/json
    tty: true
