version: '3'
services:
  
  web:
    build:
      context: .
      dockerfile: ./dockerfile/web
    volumes:
      - data/mirror:/mirror
      - data/json:/json
    port:
      - 5001:5001
  
  git:
    build:
      context: .
      dockerfile: ./dockerfile/git
    volumes:
      - data/mirror:/mirror
      - data/json:/json
  
  httrack:
    build:
      context: .
      dockerfile: ./dockerfile/httrack
    volumes:
      - data/mirror:/mirror
      - data/json:/json
volumes:
  data:
    driver: local
    localPath: ./data
    mode: rw
