# Lines starting with # are comments

# Always extract audio
-x

# Do not copy the mtime
--no-mtime

# Use this proxy
#--proxy 127.0.0.1:3128

# Save all videos under YouTube directory in your home directory
-o ~/YouTube/%(title)s.%(ext)s

# Number of concurrent fragments
-N 4

# Maximum download rate
-r 8M

# Throttled download rate
--throttled-rate 200K

# Number of retries
-R 5

# Number of file access retries
--file-access-retries 3

# Number of fragment retries
--fragment-retries 5

# Retry sleep time
--retry-sleep linear=1::2

# Do not keep fragments
--no-keep-fragments

# Buffer size
--buffer-size 1024

# HTTP chunk size
--http-chunk-size 10M

# Download paths
-P /mirror/youtube/

# Do not overwrite files
-w

# Continue downloading partial files
-c

# Do not use .part files
--no-part

# Write video description
--write-description

# Do not clean infojson
--no-clean-info-json
